/* ! All generated by AI ! */

#include "pcr_crypto.h"

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>

bool CryptoUtils::GenerateX25519KeyPair(std::vector<uint8_t> &out_priv_key, std::vector<uint8_t> &out_pub_key)
{
	EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_X25519, nullptr);
	EVP_PKEY *pkey = nullptr;
	bool success = false;

	if(pctx && EVP_PKEY_keygen_init(pctx) > 0 && EVP_PKEY_keygen(pctx, &pkey) > 0)
	{
		size_t priv_len = 32, pub_len = 32;
		out_priv_key.resize(priv_len);
		out_pub_key.resize(pub_len);

		if(EVP_PKEY_get_raw_private_key(pkey, out_priv_key.data(), &priv_len) > 0 &&
			EVP_PKEY_get_raw_public_key(pkey, out_pub_key.data(), &pub_len) > 0)
		{
			success = true;
		}
	}
	if(pkey)
		EVP_PKEY_free(pkey);
	if(pctx)
		EVP_PKEY_CTX_free(pctx);
	return success;
}

bool CryptoUtils::X25519_Encrypt(const std::vector<uint8_t> &receiver_pub_bytes,
	const std::vector<uint8_t> &plaintext,
	std::vector<uint8_t> &out_packet)
{
	EVP_PKEY *receiver_pub = nullptr;
	EVP_PKEY_CTX *pctx = nullptr;
	EVP_PKEY *ephemeral_key = nullptr;
	EVP_CIPHER_CTX *cipher_ctx = nullptr;
	size_t secret_len = 0;
	size_t pub_len = 32;
	int len = 0, final_len = 0;
	bool success = false;

	std::vector<uint8_t> shared_secret;
	std::vector<uint8_t> ephemeral_pub(32);
	std::vector<uint8_t> iv(12);
	std::vector<uint8_t> tag(16);
	std::vector<uint8_t> ciphertext(plaintext.size());
	uint8_t aes_key[32];

	receiver_pub = EVP_PKEY_new_raw_public_key(EVP_PKEY_X25519, nullptr, receiver_pub_bytes.data(), receiver_pub_bytes.size());
	pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_X25519, nullptr);

	if(!receiver_pub || !pctx || EVP_PKEY_keygen_init(pctx) <= 0 || EVP_PKEY_keygen(pctx, &ephemeral_key) <= 0)
		goto cleanup;
	EVP_PKEY_CTX_free(pctx);
	pctx = nullptr;

	pctx = EVP_PKEY_CTX_new(ephemeral_key, nullptr);
	if(!pctx || EVP_PKEY_derive_init(pctx) <= 0 || EVP_PKEY_derive_set_peer(pctx, receiver_pub) <= 0 || EVP_PKEY_derive(pctx, nullptr, &secret_len) <= 0)
		goto cleanup;
	shared_secret.resize(secret_len);
	if(EVP_PKEY_derive(pctx, shared_secret.data(), &secret_len) <= 0)
		goto cleanup;

	SHA256(shared_secret.data(), shared_secret.size(), aes_key);

	EVP_PKEY_get_raw_public_key(ephemeral_key, ephemeral_pub.data(), &pub_len);

	RAND_bytes(iv.data(), iv.size());
	cipher_ctx = EVP_CIPHER_CTX_new();
	if(!cipher_ctx ||
		EVP_EncryptInit_ex(cipher_ctx, EVP_aes_256_gcm(), nullptr, aes_key, iv.data()) <= 0 ||
		EVP_EncryptUpdate(cipher_ctx, ciphertext.data(), &len, plaintext.data(), plaintext.size()) <= 0 ||
		EVP_EncryptFinal_ex(cipher_ctx, ciphertext.data() + len, &final_len) <= 0 ||
		EVP_CIPHER_CTX_ctrl(cipher_ctx, EVP_CTRL_AEAD_GET_TAG, 16, tag.data()) <= 0)
		goto cleanup;

	out_packet.clear();
	out_packet.insert(out_packet.end(), ephemeral_pub.begin(), ephemeral_pub.end());
	out_packet.insert(out_packet.end(), iv.begin(), iv.end());
	out_packet.insert(out_packet.end(), tag.begin(), tag.end());
	out_packet.insert(out_packet.end(), ciphertext.begin(), ciphertext.end());
	success = true;

cleanup:
	if(receiver_pub)
		EVP_PKEY_free(receiver_pub);
	if(ephemeral_key)
		EVP_PKEY_free(ephemeral_key);
	if(pctx)
		EVP_PKEY_CTX_free(pctx);
	if(cipher_ctx)
		EVP_CIPHER_CTX_free(cipher_ctx);
	return success;
}

bool CryptoUtils::X25519_Decrypt(const std::vector<uint8_t> &my_priv_bytes,
	const std::vector<uint8_t> &packet,
	std::vector<uint8_t> &out_plaintext)
{
	if(packet.size() < (32 + 12 + 16))
		return false;

	EVP_PKEY *my_priv = nullptr;
	EVP_PKEY *ephemeral_pub = nullptr;
	EVP_PKEY_CTX *pctx = nullptr;
	EVP_CIPHER_CTX *cipher_ctx = nullptr;
	size_t secret_len = 0;
	int len = 0, final_len = 0;
	bool success = false;

	std::vector<uint8_t> ephemeral_pub_bytes(packet.begin(), packet.begin() + 32);
	std::vector<uint8_t> iv(packet.begin() + 32, packet.begin() + 32 + 12);
	std::vector<uint8_t> tag(packet.begin() + 32 + 12, packet.begin() + 32 + 12 + 16);
	std::vector<uint8_t> ciphertext(packet.begin() + 32 + 12 + 16, packet.end());
	std::vector<uint8_t> shared_secret;
	uint8_t aes_key[32];

	my_priv = EVP_PKEY_new_raw_private_key(EVP_PKEY_X25519, nullptr, my_priv_bytes.data(), my_priv_bytes.size());
	ephemeral_pub = EVP_PKEY_new_raw_public_key(EVP_PKEY_X25519, nullptr, ephemeral_pub_bytes.data(), ephemeral_pub_bytes.size());

	if(!my_priv || !ephemeral_pub)
		goto cleanup;

	pctx = EVP_PKEY_CTX_new(my_priv, nullptr);
	if(!pctx || EVP_PKEY_derive_init(pctx) <= 0 || EVP_PKEY_derive_set_peer(pctx, ephemeral_pub) <= 0 || EVP_PKEY_derive(pctx, nullptr, &secret_len) <= 0)
		goto cleanup;
	shared_secret.resize(secret_len);
	if(EVP_PKEY_derive(pctx, shared_secret.data(), &secret_len) <= 0)
		goto cleanup;

	SHA256(shared_secret.data(), shared_secret.size(), aes_key);

	cipher_ctx = EVP_CIPHER_CTX_new();
	out_plaintext.resize(ciphertext.size());
	if(!cipher_ctx ||
		EVP_DecryptInit_ex(cipher_ctx, EVP_aes_256_gcm(), nullptr, aes_key, iv.data()) <= 0 ||
		EVP_DecryptUpdate(cipher_ctx, out_plaintext.data(), &len, ciphertext.data(), ciphertext.size()) <= 0 ||
		EVP_CIPHER_CTX_ctrl(cipher_ctx, EVP_CTRL_AEAD_SET_TAG, 16, tag.data()) <= 0 ||
		EVP_DecryptFinal_ex(cipher_ctx, out_plaintext.data() + len, &final_len) <= 0)
		goto cleanup;

	out_plaintext.resize(len + final_len);
	success = true;

cleanup:
	if(my_priv)
		EVP_PKEY_free(my_priv);
	if(ephemeral_pub)
		EVP_PKEY_free(ephemeral_pub);
	if(pctx)
		EVP_PKEY_CTX_free(pctx);
	if(cipher_ctx)
		EVP_CIPHER_CTX_free(cipher_ctx);
	return success;
}

bool CryptoUtils::GenerateAESKey(std::vector<uint8_t> &out_aes_key)
{
	out_aes_key.resize(32);
	return RAND_bytes(out_aes_key.data(), out_aes_key.size()) == 1;
}

bool CryptoUtils::AES_Encrypt(const std::vector<uint8_t> &aes_key,
	const std::vector<uint8_t> &plaintext,
	std::vector<uint8_t> &out_packet)
{
	std::vector<uint8_t> iv(12), tag(16), ciphertext(plaintext.size());
	RAND_bytes(iv.data(), iv.size());

	EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
	int len, final_len;
	bool success = false;

	if(ctx && EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), nullptr, aes_key.data(), iv.data()) > 0 &&
		EVP_EncryptUpdate(ctx, ciphertext.data(), &len, plaintext.data(), plaintext.size()) > 0 &&
		EVP_EncryptFinal_ex(ctx, ciphertext.data() + len, &final_len) > 0 &&
		EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_GET_TAG, 16, tag.data()) > 0)
	{
		out_packet.clear();
		out_packet.insert(out_packet.end(), iv.begin(), iv.end());
		out_packet.insert(out_packet.end(), tag.begin(), tag.end());
		out_packet.insert(out_packet.end(), ciphertext.begin(), ciphertext.end());
		success = true;
	}
	if(ctx)
		EVP_CIPHER_CTX_free(ctx);
	return success;
}

bool CryptoUtils::AES_Decrypt(const std::vector<uint8_t> &aes_key,
	const std::vector<uint8_t> &packet,
	std::vector<uint8_t> &out_plaintext)
{
	if(packet.size() < (12 + 16))
		return false;

	std::vector<uint8_t> iv(packet.begin(), packet.begin() + 12);
	std::vector<uint8_t> tag(packet.begin() + 12, packet.begin() + 12 + 16);
	std::vector<uint8_t> ciphertext(packet.begin() + 12 + 16, packet.end());

	EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
	out_plaintext.resize(ciphertext.size());
	int len, final_len;
	bool success = false;

	if(ctx && EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), nullptr, aes_key.data(), iv.data()) > 0 &&
		EVP_DecryptUpdate(ctx, out_plaintext.data(), &len, ciphertext.data(), ciphertext.size()) > 0 &&
		EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, 16, tag.data()) > 0 &&
		EVP_DecryptFinal_ex(ctx, out_plaintext.data() + len, &final_len) > 0)
	{
		out_plaintext.resize(len + final_len);
		success = true;
	}
	if(ctx)
		EVP_CIPHER_CTX_free(ctx);
	return success;
}

unsigned char *CryptoUtils::CU_SHA256(const unsigned char *d, size_t n, unsigned char *md)
{
	return SHA256(d, n, md);
}
